### ISSUE TITLE
Issue with deploying front-end

### ISSUE THREAD

**Issue by shardi-b** [aws-samples/amazon-chime-sdk-meetings-breakout-rooms#3]
Hello, I tried using this CDK to create breakout rooms for my team's meetings but unfortunately, while the backend did deploy, I ran into an error when the front end tried to deploy.
```
[/Users/<username>/Documents/amazon-chime-sdk-meetings-breakout-rooms/front-end-resources/react-meeting/src/containers/BreakoutControls/BreakoutModal.tsx
TypeScript error in /Users/beshard/Documents/amazon-chime-sdk-meetings-breakout-rooms/front-end-resources/react-meeting/src/containers/BreakoutControls/BreakoutModal.tsx(52,28):
Object is of type 'unknown'.  TS2571

    50 |       }
    51 |       catch (error) {
  > 52 |         updateErrorMessage(error.message);
       |                                                  ^
    53 |       }
    54 |     }
    55 |]([url](url))
```
I made sure that my node compatibility was correct, I'm using node v16.3.0, I'm using my own AWS account for `CDK_DEFAULT_ACCOUNT` environment variable. I also bootstrapped my cdk with the recommended variables. Let me know if you would like any more information, I think this is a fantastic feature and I'm looking forward to being able to use this normally!

**Comment by schuettc** [comment]
#2 should resolve your issue.  If you're still having issues, please let me know.  Thanks!
