### ISSUE TITLE
Error when trying to deploy. (Frontend)

### ISSUE THREAD

**Issue by kodai305** [aws-samples/amazon-chime-sdk-meetings-breakout-rooms#4]
## what I tryed

```
./deploy.sh
```

## Occurring event.

```
  :
 Building React App

~/work3/amazon-chime-sdk-meetings-breakout-rooms/front-end-resources/react-meeting ~/work3/amazon-chime-sdk-meetings-breakout-rooms

up to date, audited 3731 packages in 15s

184 packages are looking for funding
  run `npm fund` for details

58 vulnerabilities (7 moderate, 42 high, 9 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> react-meeting@0.1.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

/Users/takagikoudai/work3/amazon-chime-sdk-meetings-breakout-rooms/front-end-resources/react-meeting/src/app.tsx
TypeScript error in /Users/takagikoudai/work3/amazon-chime-sdk-meetings-breakout-rooms/front-end-resources/react-meeting/src/app.tsx(29,8):
Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.  TS2559

    27 |   <Router>
    28 |     <AppStateProvider>
  > 29 |       <Theme>
       |        ^
    30 |         <NotificationProvider>
    31 |           <Notifications />
    32 |           <ErrorProvider> 
```

## environment

 - node14.x, node16.x, node18.x
 - typescript: "3.3.1 - 4.4.0"

It was not possible to use any version.

**Comment by devalevenkatesh** [comment]
Could you check what is your React version?

Tagging @schuettc to check more.

**Comment by devalevenkatesh** [comment]
This error is due to React 18 version. The component library has not yet upgraded to React 18 due to the breaking changes in types which you are seeing. Suggest downgrading to React 17. If you are using Create-React-App then you may have to use older version of CRA dependency as even though `react` and `react-dom` are downgraded to 17 in `package.json` it still runs into same errors.

There are multiple public reports for the same issue on CRA side as well.

**Comment by dobeerman** [comment]
The same issue for react 16

package.json (npm react package)
```json
...
  "version": "16.14.0"
...
```

### Solution

add dev dependencies 

```bash
    "@types/react": "16.8.3",
    "@types/react-dom": "16.8.1",
```

also, there is the issue with the `useRef` hook in the `front-end-resources/react-meeting/src/components/DeviceSelection/MicrophoneDevices/MicrophoneActivityPreviewBar.tsx` file.

Changes proposal is to add `null` as an argument.

```tsx
  const activityBarRef = useRef<HTMLDivElement>(null);
```
